#!/usr/bin/env bash

declare -a DIR={
'/',
'/home',
'/opt',
'/usr',
'/mnt'
}

echo $DIR 2&1>/dev/null

read -r "Enter the name of the file to locate and execute: " file
echo $file 2&1>/dev/null

find $DIR -name $file -okdir |
  while IFS= read -r -d $file; do
	for $file in $DIR; do
	  if [ $(jobs -r | wc -l) -ge 5 ]; then
		wait $(jobs -r -p | head -1)
	  fi
	  (echo "Begin processing $file $(python3.6 $file $@)"; sleep 5; echo "Done with $file")&
	done
  done
fi
